### ISSUE TITLE
Add a footer to the website

### ISSUE THREAD

**Issue by NitinMadhukar** [opencodeiiita/Portal#1]

**Comment by ananya-mohanty** [comment]
Can I work on this?

**Comment by garvitchittora** [comment]
I want to work on this project

**Comment by sanskar-p** [comment]
Can I please work on this?

**Comment by thesmallstar** [comment]
assigned to @ananya-mohanty

**Comment by ujjwal-batra** [comment]
@ananya-mohanty updates??

**Comment by pradhuman1** [comment]
can i claim this issue

**Comment by thenullterminator** [comment]
@ananya-mohanty Any updates??

**Comment by thenullterminator** [comment]
Due to inactivity issue is re-assigned to @pradhuman1

**Comment by thenullterminator** [comment]
Due to inactivity issue is being assigned to @garvitchittora

**Comment by Saggittarius-A** [comment]
claim

**Comment by cyber-venom003** [comment]
__CLAIM__
