### ISSUE TITLE
add new page with sign up form

### ISSUE THREAD

**Issue by NitinMadhukar** [opencodeiiita/Portal#12]

**Comment by roshnidesigns** [comment]
claim

**Comment by NitinMadhukar** [comment]
@tinycosmos  assigned

**Comment by thenullterminator** [comment]
@tinycosmos Make sure you have a name,email and password field , along with 3 buttons one for register, other for join with google and last one for join with github.

**Comment by JLodha** [comment]
claim

**Comment by tinycosmos** [comment]
https://tinycosmos.github.io/Portal/signup
