### ISSUE TITLE
improve the design for the front page

### ISSUE THREAD

**Issue by NitinMadhukar** [opencodeiiita/Portal#13]

**Comment by Codedude1** [comment]
# claim

**Comment by kavi-12** [comment]
claim

**Comment by thenullterminator** [comment]
assigned to @Codedude1 start working :)

**Comment by roshnidesigns** [comment]
claim

**Comment by thenullterminator** [comment]
@Codedude1 updates???

**Comment by NitinMadhukar** [comment]
updates??  @Codedude1 Please reply before 1 am tomorrow , otherwise I'll have to reassign this issue to someone.

**Comment by Codedude1** [comment]
@NitinMadhukar sir, I am currently working on it. I'll try to complete it before 1 AM.

**Comment by infern018** [comment]
Claim

**Comment by NitinMadhukar** [comment]
assigned to @kavi-12
