### ISSUE TITLE
add header in mobile view

### ISSUE THREAD

**Issue by ujjwal-batra** [opencodeiiita/Portal#14]

**Comment by Cybertron-Avneesh** [comment]
Claim

**Comment by sarthakm21** [comment]
claim

**Comment by ujjwal-batra** [comment]
@Cybertron-Avneesh assigned

**Comment by JLodha** [comment]
claim

**Comment by ujjwal-batra** [comment]
@Cybertron-Avneesh updates?

**Comment by JLodha** [comment]
Can i claim it? @ujjwal-batra

**Comment by Cybertron-Avneesh** [comment]
@ujjwal-batra  
sir need a little more time.

**Comment by infern018** [comment]
Claim

**Comment by blaze-assault** [comment]
Can i claim this

**Comment by thenullterminator** [comment]
@Cybertron-Avneesh updates??

**Comment by JLodha** [comment]
Sir I want to work on this.
Its already been two days since it was last assigned

**Comment by smcri** [comment]
claim

**Comment by NitinMadhukar** [comment]
@Cybertron-Avneesh Please reply before 11:30 pm today, otherwise I'll have to reassign this issue to someone.

**Comment by ujjwal-batra** [comment]
@JLodha start working :)

**Comment by sarthakm21** [comment]
@ujjwal-batra Sir, I was the second one to comment on this so I should have been assigned this issue...........

**Comment by blaze-assault** [comment]
@ujjwal-batra  sir  i claimed this before jlodha did so it should be assigned to me.

**Comment by sggts04** [comment]
can I work on this?

**Comment by blaze-assault** [comment]
Can i claim this .it has been inactive 
@ujjwal-batra

**Comment by sarthakm21** [comment]
@ujjwal-batra Now can I take it up ??

**Comment by blaze-assault** [comment]
Claim .sir it has been inactive for a long time .

**Comment by sarthakm21** [comment]
@NitinMadhukar it has only been one day. 
![Screenshot_2020-01-29-17-33-38-56](https://user-images.githubusercontent.com/58396189/73355207-94261f80-42bd-11ea-9bc9-6a9fc855b35d.png)
