### ISSUE TITLE
give a name for the portal

### ISSUE THREAD

**Issue by ujjwal-batra** [opencodeiiita/Portal#15]
suggest an innovative name for the portal. 
the best name will be awarded the points

----comment the names in this issue

**Comment by CadencePrestissimo** [comment]
nexus

**Comment by sggts04** [comment]
ResourceHub

**Comment by Codedude1** [comment]
# NerdSpace

**Comment by pradhuman1** [comment]
CodeTreasure

**Comment by smcri** [comment]
Solaris

**Comment by roshnidesigns** [comment]
ResóStock

**Comment by sandy9808** [comment]
**FOSSNOW**

**Comment by sandy9808** [comment]
**STUDYHUB**

**Comment by Atsurak** [comment]
GeekSpace

**Comment by Saggittarius-A** [comment]
YourProf

**Comment by thenullterminator** [comment]
Great response till now 😃.
Do not stop with one you can even suggest more than one.
Just be as creative as possible.
We will be closing this issue tomorrow. So hurry up Guys.

**Comment by sanskar-p** [comment]
"Take a <br>"

**Comment by sanskar-p** [comment]
"Take a < br >"

(Without the spaces.)

**Comment by sggts04** [comment]
BunkSolutions

**Comment by shahidsiddiqui786** [comment]
**DebugEntity**

**Comment by shahidsiddiqui786** [comment]
CodeHub

**Comment by uglyprincess** [comment]
Skynet

**Comment by Cybertron-Avneesh** [comment]
reSource-Code

**Comment by shuba400** [comment]
**DeveloperHaven**

**Comment by cyber-venom003** [comment]
Geeks' Drive

**Comment by itshikhar** [comment]
GoGit

**Comment by prince-7** [comment]
Re-Source-Stock

**Comment by rox999** [comment]
TEAM hub : Together we can achieve

**Comment by AlacritousCreature** [comment]
Richie's_Rich_Resources.(RRR)

**Comment by sarthakm21** [comment]
LastMinutePrep

**Comment by ananya-mohanty** [comment]
- Panacea

- SemStock

- AcadPort

**Comment by sarthakm21** [comment]
SendNotes

**Comment by pra1hamesh** [comment]
### **BunkDazE**

**Comment by NitinMadhukar** [comment]
@Codedude1 you will get the points.
