### ISSUE TITLE
Add validation to sign up page

### ISSUE THREAD

**Issue by thenullterminator** [opencodeiiita/Portal#23]
Make sure proper error messages are displayed.(using HTML only)

**Comment by sanskar-p** [comment]
Claim

**Comment by thenullterminator** [comment]
@sanskar-p start working :)

**Comment by ananya-mohanty** [comment]
Claim

**Comment by ananya-mohanty** [comment]
Its been two days, can I work on this?

**Comment by sanskar-p** [comment]
Sir, do I have to use js for this?

**Comment by thenullterminator** [comment]
@ananya-mohanty  assigned to u.
@sanskar-p next time try completing the issues you are assigned within the time frame

**Comment by sanskar-p** [comment]
> @ananya-mohanty assigned to u.
> @sanskar-p next time try completing the issues you are assigned within the time frame

Sir, I thought we were given 48 hours.

**Comment by thenullterminator** [comment]
@sanskar-p  Don't worry we have a hell lot of issues ahead

**Comment by thenullterminator** [comment]
@ananya-mohanty it will better if you use  jQuery (cause its damn easy and readable)

**Comment by thenullterminator** [comment]
@ananya-mohanty check out the updated description
