### ISSUE TITLE
Add google/github sign in option on login page

### ISSUE THREAD

**Issue by thenullterminator** [opencodeiiita/Portal#25]

**Comment by sanskar-p** [comment]
claim

**Comment by cyber-venom003** [comment]
Claim....I wanna work on this

**Comment by sarthakm21** [comment]
Claim

**Comment by ananya-mohanty** [comment]
Claim

**Comment by ujjwal-batra** [comment]
@sanskar-p assigned

**Comment by sanskar-p** [comment]
Sir, should I make a new login page from scratch?

**Comment by sanskar-p** [comment]
Sir, can I use my own google account to integrate google sign-in?

**Comment by thenullterminator** [comment]
Just add buttons. No implementation is required

**Comment by sanskar-p** [comment]
> Just add buttons. No implementation is required

Sir, buttons have already been added.

**Comment by thenullterminator** [comment]
On login page not sign up page

**Comment by cyber-venom003** [comment]
Please assign it to me sir!!!
