### ISSUE TITLE
Create a new google account 

### ISSUE THREAD

**Issue by thenullterminator** [opencodeiiita/Portal#33]
We will be using **firebase** in the next phase of this project. So we will definitely need a test account which everyone here can access and use it to get comfortable with this amazing tool. So create one and comment the credentials.

**NOTE:**
We are assuming that everyone here are mature enough to follow **developer ethics** and not use the account for any sort **personal usage**.

**Comment by CadencePrestissimo** [comment]
claim

**Comment by sggts04** [comment]
Email: portal.test.oc@gmail.com
Password: portal-test-pass

**Comment by pradhuman1** [comment]
claim

**Comment by cyber-venom003** [comment]
__CLAIM__

**Comment by Codedude1** [comment]
claim

**Comment by mendelevium28** [comment]
claim
