### ISSUE TITLE
Getting started with firebase

### ISSUE THREAD

**Issue by thenullterminator** [opencodeiiita/Portal#39]
1:) Login into the firebase console with the credentials given in the read me.
2:) Create a new **web** project and give it an appropriate name.
3:) In index.html file include the entire Firebase JavaScript SDK in plain words add scripts inside the body tags.
4:) Create a new js file in the same directory (name it firebase_init.js) and copy into it the firebase config object (which you will encounter as soons as you will create a new web project) containing api key, auth domain etc.
That's it. 
PS: Refer official **[firebase documentation](https://firebase.google.com/docs?authuser=0)**.

**Comment by ananya-mohanty** [comment]
claim

**Comment by thenullterminator** [comment]
@ananya-mohanty start working :)

**Comment by JLodha** [comment]
Claim

**Comment by thenullterminator** [comment]
@ananya-mohanty status??

**Comment by JLodha** [comment]
Sir can i work?

**Comment by ananya-mohanty** [comment]
The work is done but cannot squash commits due to an error.
