### ISSUE TITLE
loading error

### ISSUE THREAD

**Issue by NitinMadhukar** [opencodeiiita/Portal#4]

**Comment by sanskar-p** [comment]
claim

**Comment by NitinMadhukar** [comment]
@sanskar-p assigned to you

**Comment by sanskar-p** [comment]
It shows error 404
[https://sanskar-p.github.io/Portal/](url)

<img width="960" alt="Annotation 2020-01-18 151858" src="https://user-images.githubusercontent.com/54014518/72661897-f81b2f00-3a05-11ea-8355-910671e25856.png">
