### ISSUE TITLE
Make a logo for NerdSpace

### ISSUE THREAD

**Issue by NitinMadhukar** [opencodeiiita/Portal#45]
Use the required information and make a logo in the png format. Comment down your art.

**Comment by pra1hamesh** [comment]
claim

**Comment by cyber-venom003** [comment]
__CLAIM__

**Comment by infern018** [comment]
Claim

**Comment by blaze-assault** [comment]
Claim

**Comment by NitinMadhukar** [comment]
@Lulz5ec go ahead :)

**Comment by thenullterminator** [comment]
Let's keep this open for all. Best artwork will be given points.

**Comment by NitinMadhukar** [comment]
any updates?  
comment down your art.

**Comment by griffy06** [comment]
![NerdSpace_logo](https://user-images.githubusercontent.com/45875364/73596558-f8a8df00-4548-11ea-9542-6854c8a73f77.png)

**Comment by garvitchittora** [comment]
LOGO FOR NERDSPACE .

![Screenshot (94)](https://user-images.githubusercontent.com/54021348/73725287-1184e080-4753-11ea-8998-3ac18d24682c.png)

**Comment by infinity-star** [comment]
![logo](https://user-images.githubusercontent.com/58394522/73824150-ac4af100-481f-11ea-883c-5d9a41ed8a6a.png)

**Comment by roshnidesigns** [comment]
![nerdspace](https://user-images.githubusercontent.com/45714224/73964090-903a7300-4937-11ea-98cd-ec1f22e4d2e4.jpg)

**Comment by sarthakm21** [comment]
![ns](https://user-images.githubusercontent.com/58396189/74078085-1a73fb80-4a4c-11ea-9e71-b4507d9deadc.png)
