### ISSUE TITLE
Improve the overall site 

### ISSUE THREAD

**Issue by NitinMadhukar** [opencodeiiita/Portal#58]
put the logo where needed and improve the footer and link the pages

**Comment by blaze-assault** [comment]
Claim

**Comment by aarpit1010** [comment]
Claim

**Comment by NitinMadhukar** [comment]
@blaze-assault go ahead!
Do it asap

**Comment by sarthakm21** [comment]
Claim

**Comment by blaze-assault** [comment]
@NitinMadhukar  sir what to improve in footer.

**Comment by blaze-assault** [comment]
@NitinMadhukar  please review

**Comment by blaze-assault** [comment]
https://blaze-assault.github.io/NerdSpace11/
