### ISSUE TITLE
Add a dashboard

### ISSUE THREAD

**Issue by NitinMadhukar** [opencodeiiita/Portal#6]
make another page similar to the landing page and also contains upload button

**Comment by sggts04** [comment]
claim

**Comment by sggts04** [comment]
@NitinMadhukar what exactly to put in the Dashboard?

**Comment by NitinMadhukar** [comment]
@sggts04 remove the upload button from the landing page and then put it on a new page

**Comment by NitinMadhukar** [comment]
share the live link

**Comment by sggts04** [comment]
PR mein mentioned hai

https://shreyasgupta.in/Portal/dashboard.html
